#                           -*- mode: makefile -*-

# directory type (p=project, c=category, d=directory, and s=stub
TYPE=s

# include GTD's generic Makefile
ifneq ("$(shell ls | grep Makefile.tmpl | wc -l)","0")
include ./Makefile.tmpl
else
include /usr/share/gtd-2/templates/Makefile.tmpl
endif

#GTD_LATEX = xelatex # pdflatex default

# beginning of user defined/modified settings
all::

