</$objtype/mkfile

TARG = \
	mp-writer\

BIN = /$objtype/bin

</sys/src/cmd/mkmany


regress:V: all
	rc mpipefs.rc
	rc execfs.rc
	rc gangfs.rc

debug:V: all
	#rc mpipefs.rc 9
	rc execfs.rc 9
	#rc gangfs.rc 9

tidy:VE:
	rm -f /srv/mpipe
	kill execcmd | rc
	kill gangfs | rc
	kill execfs | rc
	kill mpipefs | rc
	kill 8.execcmd | rc
	kill 8.gangfs | rc
	kill 8.execfs | rc
	kill 8.mpipefs | rc
	broke | rc
	rm -f *.log
	rm -f *.acid
   	rm -rf .test
	
	unmount /proc
	bind '#p' /proc

acid:V: execfs.acid execcmd.acid mpipefs.acid gangfs.acid
