</$objtype/mkfile

DIRS = \

TARG = \
	mp-writer\

</sys/src/cmd/mkmany

dirsclean:V: clean
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

dirsnuke:V: nuke
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

regress:V: all
	#rc mpipefs.rc
	#rc execfs.rc
	rc gangfs.rc

debug:V: all
	#rc mpipefs.rc 9
	#rc execfs.rc 9
	#rc gangfs.rc 9
	rc uem_hier.rc 9
	#rc uem_512.rc 9

tidy:VE: 
	rm -f /srv/mpipe
	kill $O.execcmd | rc
	kill $O.gangfs | rc
	kill $O.execfs | rc
	kill $O.mpipefs | rc
	kill exportfs | rc
	
	broke | rc
	rm -f *.log
	rm -f *.acid
	rm -rf .test
	
	unmount /proc
	bind '#p' /proc

acid:V: execfs.acid execcmd.acid mpipefs.acid gangfs.acid

clean:
	rm -f *.[$OS] *.a[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* $TARG $CLEANFILES
	rm -f *.log

nuke:V:
	rm -f *.[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* *.acid $TARG
	rm -f *.log
