CC=/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-gcc
CFLAGS=-Dcnk
LIBS=../../../rompilib.a
all: msgrate

msgrate: msgrate.o ../../../rompilib.a
	$(CC) -Wall -o msgrate msgrate.o ../../../rompilib.a
	cp msgrate ~/rompi

msgrate.o: msgrate.c
	$(CC) -I ../../.. -c msgrate.c
clean: 
	rm *.a *.o 
