</$objtype/mkfile

TARG = \
	csrv\
	mpipefs\
	execfs\
	execcmd\
	gangfs\

HFILES = debug.h

DIRS = tests

</sys/src/cmd/mkmany

dist:V: nuke dirsnuke
	rm *.log

dirs:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS all
	}
	cd $p

dirsinstall:V: install
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS install
	}
	cd $p

dirsclean:V: clean
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

dirsnuke:V: nuke
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

debug regress:VE: all
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

tidy:VE:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p
	rm -f /srv/mpipe
	kill execcmd | rc
	kill gangfs | rc
	kill execfs | rc
	kill mpipefs | rc
	kill exportfs | rc
	
	broke | rc
	rm -f *.log
	rm -f *.acid
	rm -rf .test .meta
	
	rm -f /srv/mpipe*
	rm -f /srv/execfs*
	rm -f /srv/gangfs*
	rm -f /srv/master
	rm -f /srv/child
	
	unmount /proc
	bind '#p' /proc

acid:V: execfs.acid execcmd.acid mpipefs.acid gangfs.acid

clean:
	rm -f *.[$OS] *.a[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* $TARG $CLEANFILES
	rm -f *.log

nuke:V:
	rm -f *.[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* *.acid $TARG
	rm -f *.log
