</$objtype/mkfile

BIN=/$objtype/bin

TARG = \
	csrv\
	mpipefs\
	execfs\
	exec2fs\
	execcmd\
	gangfs\
	gang2fs\
	poke\

HFILES = debug.h\
       timeit.h

DIRS = tests

</sys/src/cmd/mkmany

dist:V: nuke dirsnuke
	rm *.log

dirs:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS all
	}
	cd $p

dirsinstall:V: install
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS install
	}
	cd $p

dirsclean:V: clean
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

dirsnuke:V: nuke
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

debug regress test_simple test_medium test_big test_scale:VE: all
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p

tidy:VE:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $target
	}
	cd $p
	rm -f /srv/mpipe
	kill execcmd | rc
	kill gangfs | rc
	kill execfs | rc
	kill mpipefs | rc
	kill exportfs | rc
	
	broke | rc
	rm -f *.log
	rm -f *.acid
	rm -rf .test .meta
	
	rm -f /srv/mpipe*
	rm -f /srv/execfs*
	rm -f /srv/gangfs*
	rm -f /srv/master
	rm -f /srv/child
	rm -f /srv/11.*
	rm -f /srv/io
	
	unmount /proc
	bind '#p' /proc

acid:V: execfs.acid execcmd.acid mpipefs.acid gangfs.acid

clean:
	rm -f *.[$OS] *.a[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* $TARG $CLEANFILES
	rm -f *.log

nuke:V:
	rm -f *.[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* *.acid $TARG
	rm -f *.log

deploy:V:
	objtype=power mk all
	dircp ../uem /n/9/sys/src/cmd/uem
	cp q.gangfs /n/9/power/bin/gangfs
	cp q.mpipefs /n/9/power/bin/mpipefs
	cp q.execfs /n/9/power/bin/execfs
	cp q.execcmd /n/9/power/bin/execcmd
	cp q.csrv /n/9/power/bin/csrv	

anl_mount:
	srv tcp!9.3.45.4!1127 anlgw
	mount /srv/anlgw /n/anl
	bind /n/anl/net /net

anl: profile
	objtype=power mk all
	cp q.poke /n/anl/n/local/home/ericvh/9/power/bin/poke
	cp q.gangfs /n/anl/n/local/home/ericvh/9/power/bin/gangfs
	cp q.mpipefs /n/anl/n/local/home/ericvh/9/power/bin/mpipefs
	cp q.execfs /n/anl/n/local/home/ericvh/9/power/bin/execfs
	cp q.exec2fs /n/anl/n/local/home/ericvh/9/power/bin/exec2fs
	cp q.execcmd /n/anl/n/local/home/ericvh/9/power/bin/execcmd
	cp q.csrv /n/anl/n/local/home/ericvh/9/power/bin/csrv
	
	#cd tests
	#objtype=power mk all
	#cp q.time-stat /n/anl/n/local/home/ericvh/9/power/bin/time-stat
	#cd ../
	
	cd ../exportfs
	objtype=power mk anl
	cp q.out /n/anl/n/local/home/ericvh/9/power/bin/exportfs
	

profile: anl_mount
	cp tests/profile.anl /n/anl/n/local/home/ericvh/lib/profile
	cp tests/bg_256.rc /n/anl/n/local/home/ericvh/tmp/bg_256.rc
	cp tests/bg_scale.rc /n/anl/n/local/home/ericvh/tmp/bg_scale.rc
	cp tests/bg_scale_run.rc /n/anl/n/local/home/ericvh/tmp/bg_scale_run.rc
	cp tests/tidy /n/anl/n/local/home/ericvh/tmp/tidy
	cp tests/profile.anl /n/anl/n/local/home/ericvh/tmp/profile.anl

anl_run: anl_mount
	start-res -p 6048

anl_list: anl_mount
	list-res
