</$objtype/mkfile

TARG = \
	csrv\
	mpipefs\
	execfs\
	execcmd\
	gangfs\

HFILES = debug.h
BIN = /$objtype/bin

DIRS = tests

</sys/src/cmd/mkmany

dist:V: nuke dirsnuke
	rm *.log

dirs:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS all
	}
	cd $p

dirsinstall:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS install
	}
	cd $p

dirsclean:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS clean
	}
	cd $p

dirsnuke:V:
	p=`{pwd}
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS nuke
	}
	cd $p

regress:V: install dirsinstall
	tests/mpipefs.rc
	tests/execfs.rc
	tests/gangfs.rc
