typedef void Syscall(Ar0*, va_list);

Syscall cnkuname;
Syscall	cnkbrk;
Syscall cnkopen;
Syscall syssegbrk;
Syscall cnkwritev;
Syscall cnksocketcall;
Syscall cnkgeteuid;
Syscall cnkmmap;
Syscall cnkexit;
Syscall cnksettid;
Syscall sigaction;
Syscall rt_sigprocmask;
Syscall fstat64;
Syscall returnok;
Syscall futex;
Syscall cnkgetpersonality;
Syscall cnkr2c;
Syscall cnkc2r;
Syscall cnkprocid;
Syscall cnkranks2coords;
Syscall cnkmprotect;
Syscall cnkclone;
Syscall gasm;
Syscall cnkcga;
Syscall getrusage;

extern Syscall sys_write;
extern Syscall sys_read;
extern Syscall sysopen;
extern Syscall syspread;

struct syscall {
	char*	n;
	Syscall*f;
	int narg;
	Ar0	r;
};

struct syscall cnksystab[] = {
	[4]		{"write", sys_write, 3, {.i = -1}},
	[5]		{"cnkopen", sysopen, 2, {.i = -1}},
	[24]		{"getuid", cnkgeteuid, 0, {.i = -1}},
	[45]		{"cnkbrk", cnkbrk, 1, {.i = -1}},
	[47]		{"getgid", cnkgeteuid, 0, {.i = -1}},
	[49]		{"geteuid", cnkgeteuid, 0, {.i = -1}},
	[50]		{"getegid", cnkgeteuid, 0, {.i = -1}},
	[90]		{"mmap", cnkmmap, 5, {.i = -1}},
	[122]	{"cnkuname", cnkuname, 1, {.i = -1}},
	[173]	{"sigaction", sigaction, 2, {.i = -1}},
	[174]	{"rt_sigprocmask", rt_sigprocmask, 4, {.l = -1}},
	[232]	{"cnksettid", cnksettid, 1, {.i = -1}},
	[234]	{"cnkexit", cnkexit, 1, {.i = -1}},

	[0]	{"STUBrestart_syscall", returnok, 1, {.i = 0}},
	[1]	{"STUBexit", returnok, 1, {.i = 0}},
	[2]	{"STUBfork", returnok, 1, {.i = 0}},
	[3]	{"read", sys_read, 3, {.i = 0}},

	[6]	{"STUBclose", returnok, 1, {.i = 0}},
	[7]	{"STUBwaitpid", returnok, 1, {.i = 0}},
	[8]	{"STUBcreat", returnok, 1, {.i = 0}},
	[9]	{"STUBlink", returnok, 1, {.i = 0}},
	[10]	{"STUBunlink", returnok, 1, {.i = 0}},
	[11]	{"STUBexecve", returnok, 1, {.i = 0}},
	[12]	{"STUBchdir", returnok, 1, {.i = 0}},
	[13]	{"STUBtime", returnok, 1, {.i = 0}},
	[14]	{"STUBmknod", returnok, 1, {.i = 0}},
	[15]	{"STUBchmod", returnok, 1, {.i = 0}},
	[16]	{"STUBlchown", returnok, 1, {.i = 0}},
	[17]	{"STUBbreak", returnok, 1, {.i = 0}},
	[18]	{"STUBoldstat", returnok, 1, {.i = 0}},
	[19]	{"STUBlseek", returnok, 1, {.i = 0}},
	[20]	{"STUBgetpid", returnok, 1, {.i = 0}},
	[21]	{"STUBmount", returnok, 1, {.i = 0}},
	[22]	{"STUBumount", returnok, 1, {.i = 0}},
	[23]	{"STUBsetuid", returnok, 1, {.i = 0}},

	[25]	{"STUBstime", returnok, 1, {.i = 0}},
	[26]	{"STUBptrace", returnok, 1, {.i = 0}},
	[27]	{"STUBalarm", returnok, 1, {.i = 0}},
	[28]	{"STUBoldfstat", returnok, 1, {.i = 0}},
	[29]	{"STUBpause", returnok, 1, {.i = 0}},
	[30]	{"STUButime", returnok, 1, {.i = 0}},
	[31]	{"STUBstty", returnok, 1, {.i = 0}},
	[32]	{"STUBgtty", returnok, 1, {.i = 0}},
	[33]	{"STUBaccess", returnok, 1, {.i = 0}},
	[34]	{"STUBnice", returnok, 1, {.i = 0}},
	[35]	{"STUBftime", returnok, 1, {.i = 0}},
	[36]	{"STUBsync", returnok, 1, {.i = 0}},
	[37]	{"STUBkill", returnok, 1, {.i = 0}},
	[38]	{"STUBrename", returnok, 1, {.i = 0}},
	[39]	{"STUBmkdir", returnok, 1, {.i = 0}},
	[40]	{"STUBrmdir", returnok, 1, {.i = 0}},
	[41]	{"STUBdup", returnok, 1, {.i = 0}},
	[42]	{"STUBpipe", returnok, 1, {.i = 0}},
	[43]	{"STUBtimes", returnok, 1, {.i = 0}},
	[44]	{"STUBprof", returnok, 1, {.i = 0}},

	[46]	{"STUBsetgid", returnok, 1, {.i = 0}},

	[48]	{"STUBsignal", returnok, 1, {.i = 0}},

	[51]	{"STUBacct", returnok, 1, {.i = 0}},
	[52]	{"STUBumount2", returnok, 1, {.i = 0}},
	[53]	{"STUBlock", returnok, 1, {.i = 0}},
	[54]	{"STUBioctl", returnok, 1, {.i = 0}},
	[55]	{"STUBfcntl", returnok, 1, {.i = 0}},
	[56]	{"STUBmpx", returnok, 1, {.i = 0}},
	[57]	{"STUBsetpgid", returnok, 1, {.i = 0}},
	[58]	{"STUBulimit", returnok, 1, {.i = 0}},
	[59]	{"STUBoldolduname", returnok, 1, {.i = 0}},
	[60]	{"STUBumask", returnok, 1, {.i = 0}},
	[61]	{"STUBchroot", returnok, 1, {.i = 0}},
	[62]	{"STUBustat", returnok, 1, {.i = 0}},
	[63]	{"STUBdup2", returnok, 1, {.i = 0}},
	[64]	{"STUBgetppid", returnok, 1, {.i = 0}},
	[65]	{"STUBgetpgrp", returnok, 1, {.i = 0}},
	[66]	{"STUBsetsid", returnok, 1, {.i = 0}},
	[67]	{"STUBsigaction", returnok, 1, {.i = 0}},
	[68]	{"STUBsgetmask", returnok, 1, {.i = 0}},
	[69]	{"STUBssetmask", returnok, 1, {.i = 0}},
	[70]	{"STUBsetreuid", returnok, 1, {.i = 0}},
	[71]	{"STUBsetregid", returnok, 1, {.i = 0}},
	[72]	{"STUBsigsuspend", returnok, 1, {.i = 0}},
	[73]	{"STUBsigpending", returnok, 1, {.i = 0}},
	[74]	{"STUBsethostname", returnok, 1, {.i = 0}},
	[75]	{"STUBsetrlimit", returnok, 1, {.i = 0}},
	[76]	{"STUBgetrlimit", returnok, 1, {.i = 0}},
	[77]	{"getrusage", getrusage, 1, {.i = 0}},
	[78]	{"STUBgettimeofday", returnok, 1, {.i = 0}},
	[79]	{"STUBsettimeofday", returnok, 1, {.i = 0}},
	[80]	{"STUBgetgroups", returnok, 1, {.i = 0}},
	[81]	{"STUBsetgroups", returnok, 1, {.i = 0}},
	[82]	{"STUBselect", returnok, 1, {.i = 0}},
	[83]	{"STUBsymlink", returnok, 1, {.i = 0}},
	[84]	{"STUBoldlstat", returnok, 1, {.i = 0}},
	[85]	{"STUBreadlink", returnok, 1, {.i = 0}},
	[86]	{"STUBuselib", returnok, 1, {.i = 0}},
	[87]	{"STUBswapon", returnok, 1, {.i = 0}},
	[88]	{"STUBreboot", returnok, 1, {.i = 0}},
	[89]	{"STUBreaddir", returnok, 1, {.i = 0}},

	[91]	{"STUBmunmap", returnok, 1, {.i = 0}},
	[92]	{"STUBtruncate", returnok, 1, {.i = 0}},
	[93]	{"STUBftruncate", returnok, 1, {.i = 0}},
	[94]	{"STUBfchmod", returnok, 1, {.i = 0}},
	[95]	{"STUBfchown", returnok, 1, {.i = 0}},
	[96]	{"STUBgetpriority", returnok, 1, {.i = 0}},
	[97]	{"STUBsetpriority", returnok, 1, {.i = 0}},
	[98]	{"STUBprofil", returnok, 1, {.i = 0}},
	[99]	{"STUBstatfs", returnok, 1, {.i = 0}},
	[100]	{"STUBfstatfs", returnok, 1, {.i = 0}},
	[101]	{"STUBioperm", returnok, 1, {.i = 0}},
	[102]	{"socketcall", cnksocketcall, 1, {.i = 0}},
	[103]	{"STUBsyslog", returnok, 1, {.i = 0}},
	[104]	{"STUBsetitimer", returnok, 1, {.i = 0}},
	[105]	{"STUBgetitimer", returnok, 1, {.i = 0}},
	[106]	{"STUBstat", returnok, 1, {.i = 0}},
	[107]	{"STUBlstat", returnok, 1, {.i = 0}},
	[108]	{"STUBfstat", returnok, 1, {.i = 0}},
	[109]	{"STUBolduname", returnok, 1, {.i = 0}},
	[110]	{"STUBiopl", returnok, 1, {.i = 0}},
	[111]	{"STUBvhangup", returnok, 1, {.i = 0}},
	[112]	{"STUBidle", returnok, 1, {.i = 0}},
	[113]	{"STUBvm86", returnok, 1, {.i = 0}},
	[114]	{"STUBwait4", returnok, 1, {.i = 0}},
	[115]	{"STUBswapoff", returnok, 1, {.i = 0}},
	[116]	{"STUBsysinfo", returnok, 1, {.i = 0}},
	[117]	{"STUBipc", returnok, 1, {.i = 0}},
	[118]	{"STUBfsync", returnok, 1, {.i = 0}},
	[119]	{"STUBsigreturn", returnok, 1, {.i = 0}},
	[120]	{"clone", cnkclone, 1, {.i = 0}},
	[121]	{"STUBsetdomainname", returnok, 1, {.i = 0}},

	[123]	{"STUBmodify_ldt", returnok, 1, {.i = 0}},
	[124]	{"STUBadjtimex", returnok, 1, {.i = 0}},
	[125]	{"mprotect", cnkmprotect, 1, {.i = 0}},
	[126]	{"STUBsigprocmask", returnok, 1, {.i = 0}},
	[127]	{"STUBcreate_module", returnok, 1, {.i = 0}},
	[128]	{"STUBinit_module", returnok, 1, {.i = 0}},
	[129]	{"STUBdelete_module", returnok, 1, {.i = 0}},
	[130]	{"STUBget_kernel_syms", returnok, 1, {.i = 0}},
	[131]	{"STUBquotactl", returnok, 1, {.i = 0}},
	[132]	{"STUBgetpgid", returnok, 1, {.i = 0}},
	[133]	{"STUBfchdir", returnok, 1, {.i = 0}},
	[134]	{"STUBbdflush", returnok, 1, {.i = 0}},
	[135]	{"STUBsysfs", returnok, 1, {.i = 0}},
	[136]	{"STUBpersonality", returnok, 1, {.i = 0}},
	[137]	{"STUBafs_syscall", returnok, 1, {.i = 0}},
	[138]	{"STUBsetfsuid", returnok, 1, {.i = 0}},
	[139]	{"STUBsetfsgid", returnok, 1, {.i = 0}},
	[140]	{"STUB_llseek", returnok, 1, {.i = 0}},
	[141]	{"STUBgetdents", returnok, 1, {.i = 0}},
	[142]	{"STUB_newselect", returnok, 1, {.i = 0}},
	[143]	{"STUBflock", returnok, 1, {.i = 0}},
	[144]	{"STUBmsync", returnok, 1, {.i = 0}},
	[145]	{"STUBreadv", returnok, 1, {.i = 0}},
	[146]	{"writev", cnkwritev, 1, {.i = 0}},
	[147]	{"STUBgetsid", returnok, 1, {.i = 0}},
	[148]	{"STUBfdatasync", returnok, 1, {.i = 0}},
	[149]	{"STUB_sysctl", returnok, 1, {.i = 0}},
	[150]	{"STUBmlock", returnok, 1, {.i = 0}},
	[151]	{"STUBmunlock", returnok, 1, {.i = 0}},
	[152]	{"STUBmlockall", returnok, 1, {.i = 0}},
	[153]	{"STUBmunlockall", returnok, 1, {.i = 0}},
	[154]	{"STUBsched_setparam", returnok, 1, {.i = 0}},
	[155]	{"STUBsched_getparam", returnok, 1, {.i = 0}},
	[156]	{"STUBsched_setscheduler", returnok, 1, {.i = 0}},
	[157]	{"STUBsched_getscheduler", returnok, 1, {.i = 0}},
	[158]	{"STUBsched_yield", returnok, 1, {.i = 0}},
	[159]	{"STUBsched_get_priority_max", returnok, 1, {.i = 0}},
	[160]	{"STUBsched_get_priority_min", returnok, 1, {.i = 0}},
	[161]	{"STUBsched_rr_get_interval", returnok, 1, {.i = 0}},
	[162]	{"STUBnanosleep", returnok, 1, {.i = 0}},
	[163]	{"STUBmremap", returnok, 1, {.i = 0}},
	[164]	{"STUBsetresuid", returnok, 1, {.i = 0}},
	[165]	{"STUBgetresuid", returnok, 1, {.i = 0}},
	[166]	{"STUBquery_module", returnok, 1, {.i = 0}},
	[167]	{"STUBpoll", returnok, 1, {.i = 0}},
	[168]	{"STUBnfsservctl", returnok, 1, {.i = 0}},
	[169]	{"STUBsetresgid", returnok, 1, {.i = 0}},
	[170]	{"STUBgetresgid", returnok, 1, {.i = 0}},
	[171]	{"STUBprctl", returnok, 1, {.i = 0}},
	[172]	{"STUBrt_sigreturn", returnok, 1, {.i = 0}},

	[175]	{"STUBrt_sigpending", returnok, 1, {.i = 0}},
	[176]	{"STUBrt_sigtimedwait", returnok, 1, {.i = 0}},
	[177]	{"STUBrt_sigqueueinfo", returnok, 1, {.i = 0}},
	[178]	{"STUBrt_sigsuspend", returnok, 1, {.i = 0}},
	[179]	{"pread64", syspread, 5, {.i = 0}},
	[180]	{"STUBpwrite64", returnok, 1, {.i = 0}},
	[181]	{"STUBchown", returnok, 1, {.i = 0}},
	[182]	{"STUBgetcwd", returnok, 1, {.i = 0}},
	[183]	{"STUBcapget", returnok, 1, {.i = 0}},
	[184]	{"STUBcapset", returnok, 1, {.i = 0}},
	[185]	{"STUBsigaltstack", returnok, 1, {.i = 0}},
	[186]	{"STUBsendfile", returnok, 1, {.i = 0}},
	[187]	{"STUBgetpmsg", returnok, 1, {.i = 0}},
	[188]	{"STUBputpmsg", returnok, 1, {.i = 0}},
	[189]	{"STUBvfork", returnok, 1, {.i = 0}},
	[190]	{"STUBugetrlimit", returnok, 1, {.i = 0}},
	[191]	{"STUBreadahead", returnok, 1, {.i = 0}},
	[192]	{"STUBmmap2", returnok, 1, {.i = 0}},
	[193]	{"STUBtruncate64", returnok, 1, {.i = 0}},
	[194]	{"STUBftruncate64", returnok, 1, {.i = 0}},
	[195]	{"STUBstat64", returnok, 1, {.i = 0}},
	[196]	{"STUBlstat64", returnok, 1, {.i = 0}},
	[197]	{"fstat64", fstat64, 1, {.i = -1}},
	[198]	{"STUBpciconfig_read", returnok, 1, {.i = 0}},
	[199]	{"STUBpciconfig_write", returnok, 1, {.i = 0}},
	[200]	{"STUBpciconfig_iobase", returnok, 1, {.i = 0}},
	[201]	{"STUBmultiplexer", returnok, 1, {.i = 0}},
	[202]	{"STUBgetdents64", returnok, 1, {.i = 0}},
	[203]	{"STUBpivot_root", returnok, 1, {.i = 0}},
	[204]	{"STUBfcntl64", returnok, 1, {.i = 0}},
	[205]	{"STUBmadvise", returnok, 1, {.i = 0}},
	[206]	{"STUBmincore", returnok, 1, {.i = 0}},
	[207]	{"STUBgettid", returnok, 1, {.i = 0}},
	[208]	{"STUBtkill", returnok, 1, {.i = 0}},
	[209]	{"STUBsetxattr", returnok, 1, {.i = 0}},
	[210]	{"STUBlsetxattr", returnok, 1, {.i = 0}},
	[211]	{"STUBfsetxattr", returnok, 1, {.i = 0}},
	[212]	{"STUBgetxattr", returnok, 1, {.i = 0}},
	[213]	{"STUBlgetxattr", returnok, 1, {.i = 0}},
	[214]	{"STUBfgetxattr", returnok, 1, {.i = 0}},
	[215]	{"STUBlistxattr", returnok, 1, {.i = 0}},
	[216]	{"STUBllistxattr", returnok, 1, {.i = 0}},
	[217]	{"STUBflistxattr", returnok, 1, {.i = 0}},
	[218]	{"STUBremovexattr", returnok, 1, {.i = 0}},
	[219]	{"STUBlremovexattr", returnok, 1, {.i = 0}},
	[220]	{"STUBfremovexattr", returnok, 1, {.i = 0}},
	[221]	{"futex", futex, 1, {.i = 0}},
	[222]	{"STUBsched_setaffinity", returnok, 1, {.i = 0}},
	[223]	{"STUBsched_getaffinity", returnok, 1, {.i = 0}},
	[225]	{"STUBtuxcall", returnok, 1, {.i = 0}},
	[226]	{"STUBsendfile64", returnok, 1, {.i = 0}},
	[227]	{"STUBio_setup", returnok, 1, {.i = 0}},
	[228]	{"STUBio_destroy", returnok, 1, {.i = 0}},
	[229]	{"STUBio_getevents", returnok, 1, {.i = 0}},
	[230]	{"STUBio_submit", returnok, 1, {.i = 0}},
	[231]	{"STUBio_cancel", returnok, 1, {.i = 0}},

	[233]	{"STUBfadvise64", returnok, 1, {.i = 0}},

	[235]	{"STUBlookup_dcookie", returnok, 1, {.i = 0}},
	[236]	{"STUBepoll_create", returnok, 1, {.i = 0}},
	[237]	{"STUBepoll_ctl", returnok, 1, {.i = 0}},
	[238]	{"STUBepoll_wait", returnok, 1, {.i = 0}},
	[239]	{"STUBremap_file_pages", returnok, 1, {.i = 0}},
	[240]	{"STUBtimer_create", returnok, 1, {.i = 0}},
	[241]	{"STUBtimer_settime", returnok, 1, {.i = 0}},
	[242]	{"STUBtimer_gettime", returnok, 1, {.i = 0}},
	[243]	{"STUBtimer_getoverrun", returnok, 1, {.i = 0}},
	[244]	{"STUBtimer_delete", returnok, 1, {.i = 0}},
	[245]	{"STUBclock_settime", returnok, 1, {.i = 0}},
	[246]	{"STUBclock_gettime", returnok, 1, {.i = 0}},
	[247]	{"STUBclock_getres", returnok, 1, {.i = 0}},
	[248]	{"STUBclock_nanosleep", returnok, 1, {.i = 0}},
	[249]	{"STUBswapcontext", returnok, 1, {.i = 0}},
	[250]	{"STUBtgkill", returnok, 1, {.i = 0}},
	[251]	{"STUButimes", returnok, 1, {.i = 0}},
	[252]	{"STUBstatfs64", returnok, 1, {.i = 0}},
	[253]	{"STUBfstatfs64", returnok, 1, {.i = 0}},
	[254]	{"STUBfadvise64_64", returnok, 1, {.i = 0}},
	[255]	{"STUBrtas", returnok, 1, {.i = 0}},
	[256]	{"STUBsys_debug_setcontext", returnok, 1, {.i = 0}},
	[259]	{"STUBmbind", returnok, 1, {.i = 0}},
	[260]	{"STUBget_mempolicy", returnok, 1, {.i = 0}},
	[261]	{"STUBset_mempolicy", returnok, 1, {.i = 0}},
	[262]	{"STUBmq_open", returnok, 1, {.i = 0}},
	[263]	{"STUBmq_unlink", returnok, 1, {.i = 0}},
	[264]	{"STUBmq_timedsend", returnok, 1, {.i = 0}},
	[265]	{"STUBmq_timedreceive", returnok, 1, {.i = 0}},
	[266]	{"STUBmq_notify", returnok, 1, {.i = 0}},
	[267]	{"STUBmq_getsetattr", returnok, 1, {.i = 0}},
	[268]	{"STUBkexec_load", returnok, 1, {.i = 0}},
	[269]	{"STUBadd_key", returnok, 1, {.i = 0}},
	[270]	{"STUBrequest_key", returnok, 1, {.i = 0}},
	[271]	{"STUBkeyctl", returnok, 1, {.i = 0}},
	[272]	{"STUBwaitid", returnok, 1, {.i = 0}},
	[273]	{"STUBioprio_set", returnok, 1, {.i = 0}},
	[274]	{"STUBioprio_get", returnok, 1, {.i = 0}},
	[275]	{"STUBinotify_init", returnok, 1, {.i = 0}},
	[276]	{"STUBinotify_add_watch", returnok, 1, {.i = 0}},
	[277]	{"STUBinotify_rm_watch", returnok, 1, {.i = 0}},
	[278]	{"STUBspu_run", returnok, 1, {.i = 0}},
	[279]	{"STUBspu_create", returnok, 1, {.i = 0}},
	[280]	{"STUBpselect6", returnok, 1, {.i = 0}},
	[281]	{"STUBppoll", returnok, 1, {.i = 0}},
	[282]	{"STUBunshare", returnok, 1, {.i = 0}},
	[283]	{"STUBsplice", returnok, 1, {.i = 0}},
	[284]	{"STUBtee", returnok, 1, {.i = 0}},
	[285]	{"STUBvmsplice", returnok, 1, {.i = 0}},
	[286]	{"STUBopenat", returnok, 1, {.i = 0}},
	[287]	{"STUBmkdirat", returnok, 1, {.i = 0}},
	[288]	{"STUBmknodat", returnok, 1, {.i = 0}},
	[289]	{"STUBfchownat", returnok, 1, {.i = 0}},
	[290]	{"STUBfutimesat", returnok, 1, {.i = 0}},
	[291]	{"STUBnewfstatat", returnok, 1, {.i = 0}},
	[292]	{"STUBunlinkat", returnok, 1, {.i = 0}},
	[293]	{"STUBrenameat", returnok, 1, {.i = 0}},
	[294]	{"STUBlinkat", returnok, 1, {.i = 0}},
	[295]	{"STUBsymlinkat", returnok, 1, {.i = 0}},
	[296]	{"STUBreadlinkat", returnok, 1, {.i = 0}},
	[297]	{"STUBfchmodat", returnok, 1, {.i = 0}},
	[298]	{"STUBfaccessat", returnok, 1, {.i = 0}},
	[299]	{"STUBget_robust_list", returnok, 1, {.i = 0}},
	[300]	{"STUBset_robust_list", returnok, 1, {.i = 0}},
	/* these numbers released under the CPL */
	[1024 + 0]	{"BGP_SYSCALL_NR_GET_PERSONALITY", cnkgetpersonality, 1, {.i = 0}},
	[1024 + 1]	{"STUB_BGP_SYSCALL_NR_DMA", returnok, 0, {.i = 0}},
	[1024 + 2]	{"STUB_BGP_SYSCALL_NR_GET_DEVICE_MAP", returnok, 0, {.i = 0}},
	[1024 + 4]	{"BGP_SYSCALL_NR_GET_PROCESSOR_ID", cnkprocid, 0, {.i = 0}},
	[1024 + 3]	{"STUB_BGP_SYSCALL_NR_PTHREAD_POOF  ", returnok, 0, {.i = 0}},					// see include/spi/bgp_PThreadsExtensions.h
	[1024 + 5]	{"STUB_BGP_SYSCALL_NR_GET_PROCESSOR_VER", returnok, 0, {.i = 0}},
	[1024 + 6]	{"BGP_SYSCALL_NR_ALLOC_COUNTER", cnkcga, 0, {.i = -1}},
	[1024 + 7]	{"BGP_SYSCALL_NR_COORD2RANK", cnkc2r, 0, {.i = 0}},
	[1024 + 8]	{"BGP_SYSCALL_NR_RANK2COORD", cnkr2c, 5, {.i = 0}},
	[1024 + 9]	{"STUB_BGP_SYSCALL_NR_GETJOBID", returnok, 0, {.i = 0}},
	[1024 + 10]	{"STUB_BGP_SYSCALL_NR_READDCR", returnok, 0, {.i = 0}},
	[1024 + 11]	{"STUB_BGP_SYSCALL_NR_WRITEDCR", returnok, 0, {.i = 0}},
	[1024 + 12]	{"STUB_BGP_SYSCALL_NR_COUNTERGRPALLOCATE", returnok, 0, {.i = 0}},
	[1024 + 13]	{"STUB_BGP_SYSCALL_NR_COUNTERGRPFREE", returnok, 0, {.i = 0}},
	[1024 + 14]	{"STUB_BGP_SYSCALL_NR_COUNTERGRPQUERYFREE", returnok, 0, {.i = 0}},
	[1024 + 15]	{"STUB_BGP_SYSCALL_NR_INJFIFOGRPALLOCATE", returnok, 0, {.i = 0}},
	[1024 + 16]	{"STUB_BGP_SYSCALL_NR_INJFIFOGRPFREE", returnok, 0, {.i = 0}},
	[1024 + 17]	{"STUB_BGP_SYSCALL_NR_INJFIFOGRPQUERYFREE", returnok, 0, {.i = 0}},
	[1024 + 18]	{"STUB_BGP_SYSCALL_NR_RECFIFOSETMAP", returnok, 0, {.i = 0}},
	[1024 + 19]	{"STUB_BGP_SYSCALL_NR_RECFIFOGETMAP", returnok, 0, {.i = 0}},
	[1024 + 20]	{"STUB_BGP_SYSCALL_NR_RECGETFIFOGROUP", returnok, 0, {.i = 0}},
	[1024 + 21]	{"STUB_BGP_SYSCALL_NR_RECFIFOINITID", returnok, 0, {.i = 0}},
	[1024 + 22]	{"STUB_BGP_SYSCALL_NR_INJFIFOINITID", returnok, 0, {.i = 0}},
	[1024 + 23]	{"STUB_BGP_SYSCALL_NR_CHGDMACTRINTERRUPT             ", returnok, 0, {.i = 0}},

	[1024 + 24]	{"STUB_BGP_SYSCALL_NR_ATOMIC_SWAP", returnok, 0, {.i = 0}},
	[1024 + 25]	{"STUB_BGP_SYSCALL_NR_COMPARE_AND_SWAP", returnok, 0, {.i = 0}},
	[1024 + 26]	{"STUB_BGP_SYSCALL_NR_FETCH_AND_ADD", returnok, 0, {.i = 0}},
	[1024 + 27]	{"STUB_BGP_SYSCALL_NR_FETCH_AND_DEC_POS", returnok, 0, {.i = 0}},
	[1024 + 28]	{"STUB_BGP_SYSCALL_NR_TESTBIT_AND_SWAP", returnok, 0, {.i = 0}},
	[1024 + 29]	{"STUB_BGP_SYSCALL_NR_SUBTRACT_AND_SWAP", returnok, 0, {.i = 0}},
	[1024 + 30]	{"STUB_BGP_SYSCALL_NR_CLEARFULLRECPFIFO              ", returnok, 0, {.i = 0}},
	[1024 + 31]	{"STUB_BGP_SYSCALL_NR_COMPARE_AND_SWAP2              ", returnok, 0, {.i = 0}},

	[1024 + 32]	{"STUB_BGP_SYSCALL_NR_RAWRASINJECT                   ", returnok, 0, {.i = 0}},
	[1024 + 33]	{"STUB_BGP_SYSCALL_NR_ASCIIRASINJECT                 ", returnok, 0, {.i = 0}},

	[1024 + 34]	{"STUB_BGP_SYSCALL_NR_SETCOMMTHREADCONFIG            ", returnok, 0, {.i = 0}},
	[1024 + 35]	{"STUB_BGP_SYSCALL_NR_GETCOMMTHREADCONFIG            ", returnok, 0, {.i = 0}},
	[1024 + 36]	{"STUB_BGP_SYSCALL_NR_FLUSHINTSTATE                  ", returnok, 0, {.i = 0}},
	[1024 + 37]	{"STUB_BGP_SYSCALL_NR_DELIVERCOMMSIGNAL              ", returnok, 0, {.i = 0}},
	[1024 + 38]	{"STUB_BGP_SYSCALL_NR_CHGCOREENABLES                 ", returnok, 0, {.i = 0}},
	[1024 + 39]	{"STUB_BGP_SYSCALL_NR_CHECKPOINT               ", returnok, 0, {.i = 0}},
	[1024 + 40]	{"BGP_SYSCALL_NR_GETAPPSEGMENTMAPPING           ", gasm, 0, {.i = -1}},
	[1024 + 41]	{"STUB_BGP_SYSCALL_NR_GETMEMSIZE                     ", returnok, 0, {.i = 0}},
	[1024 + 42]	{"STUB_BGP_SYSCALL_NR_SETPRWINDOW                    ", returnok, 0, {.i = 0}},
	[1024 + 43]	{"STUB_BGP_SYSCALL_NR_GETPRWINDOW                    ", returnok, 0, {.i = 0}},
	[1024 + 44]	{"STUB_BGP_SYSCALL_NR_GETPRWINDOWSLOTS               ", returnok, 0, {.i = 0}},
	[1024 + 45]	{"STUB_BGP_SYSCALL_NR_ACTIVEPROCESSCOUNT             ", returnok, 0, {.i = 0}},
	[1024 + 46]	{"STUB_BGP_SYSCALL_NR_RANKS2COORDS", cnkranks2coords, 0, {.i = 0}},
};

int ncnksyscall = nelem(cnksystab);